In [4]:
import pandas as pd
from fractions import Fraction
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm

In [43]:
path = "/Users/Jessica/Documents/ERIP2025/jazz_transcriptions/metadata.tsv"
metadata = pd.read_csv(path, sep='\t')
metadata

,rel_paths,fnames,last_mc,last_mn,KeySig,TimeSig,label_count,annotated_key,composer,workTitle,...,staff_7_ambitus,staff_7_instrument,staff_8_ambitus,staff_8_instrument,staff_9_ambitus,staff_9_instrument,transcribed_instruments,transcribed_sections,transposition,year_certain
0,by_Alexander_Booker,Snarky_Puppy-Shapons_Vindaloo,142,142,"1: 0, 113: -3, 134: 0","1: 9/8, 2: 7/8, 4: 9/8, 5: 7/8, 7: 9/8, 8: 7/8...",8,NaN,Väsen,Shapons Vindaloo,...,NaN,NaN,NaN,NaN,NaN,NaN,"ac-g, e-g, b, nyckelharpa",complete,Concert Key,1
1,by_Alexander_Booker,The_Fearless_Flyers-Ace_of_Aces,57,57,1: 3,1: 4/4,2,NaN,Smith/Dart/Wong/Lettieri/Stratton,Ace Of Aces,...,NaN,NaN,NaN,NaN,NaN,NaN,"g, b, dr",complete,Concert Key,1
2,by_Alexander_Booker,Vulfpeck-Fugue_State,71,71,1: 0,1: 4/4,13,NaN,"Woody Goss, Jack Stratton",Fugue State,...,NaN,NaN,NaN,NaN,NaN,NaN,"ep, g, b, dr",complete,Concert Key,1
3,by_Carles_Margarit,12 Keys Blues - Bob Mintzer,156,156,1: 0,1: 4/4,169,NaN,NaN,12 Keys Blues,...,NaN,NaN,NaN,NaN,NaN,NaN,ts,solo,Bb,1
4,by_Carles_Margarit,26_2 - Coltrane (Concert Key),298,297,1: -1,"1: 4/4, 296: 2/4, 298: 4/4",347,NaN,John Coltrane,26-2,...,NaN,NaN,NaN,NaN,NaN,NaN,ts,complete,Concert Key,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288,by_seemajorsheetmusic,Superstition - Stevie Wonder,89,89,1: -3,1: 4/4,402,NaN,Comp.: Stevie Wonder,Superstition,...,30-46 (Gb1-Bb2),Bass Guitar (2),51-70 (Eb3-Bb4),NaN,NaN,NaN,"as, ts, tp, tb, g, b, key",complete,"as in Eb, ts, tp in Bb, tb, g, b, key in Conce...",1
289,by_seemajorsheetmusic,The Survivor - Jan Garbarek,27,27,1: 0,1: 4/4,43,NaN,Comp.: Jan Garbarek,The Survivor,...,NaN,NaN,NaN,NaN,NaN,NaN,ts,melody,Bb,1
290,by_seemajorsheetmusic,The Vow - Ole børud,105,105,"1: -1, 49: 6",1: 4/4,160,NaN,Ole Børud,The Vow,...,28-55 (E1-G3),Bass Guitar (2),62-79 (D4-G5),NaN,NaN,NaN,"as, ts, tp, tb, dr, g, b, el-org",complete,"as in Eb, ts, tp in Bb, tb, g, b, org in Conce...",0
291,by_seemajorsheetmusic,The World is Getting Smaller - Snarky Puppy,221,221,1: 1,1: 4/4,392,NaN,Comp.: Michael League\nTranscribed & Arranged ...,The World Is Getting Smaller,...,28-60 (E1-C4),Bass Guitar (2),70-71 (Bb4-B4),Keyboard,NaN,NaN,"ss, ts, tp, tb, b, g, key, dr",complete without solos,"ss, ts, tp in Bb, tb, g, b, key in Concert Key",1
292,from_musescore.com,Snarky_Puppy_-_Shofukan,129,129,1: 0,"1: 4/4, 40: 2/4, 41: 4/4",0,NaN,Michael League,Shofukan,...,52-83 (E3-B5),B♭ Trumpet,59-81 (B3-A5),B♭ Cornet,45-64 (A2-E4),Trombone,bigband,complete,Concert Key,NaN

In [39]:
dfs = []
for row in range(metadata.shape[0]):
    base_path = "/Users/Jessica/Documents/ERIP2025/Jessica-ERIP2025/jazz_transcriptions/notes" 
    path_row = base_path + "/" + metadata.iloc[row,1] + ".tsv"
    try: 
        df = pd.read_csv(path_row, sep='\t')
        df['fnames'] = metadata.iloc[row,1]
        df['composer'] = metadata.iloc[row,8]
        dfs.append(df)
    except Exception as e:
        continue

dfs = pd.concat(dfs, ignore_index=True)

In [41]:
dfs

,mc,mn,mc_onset,mn_onset,timesig,staff,voice,duration,gracenote,nominal_duration,scalar,tied,tpc,midi,volta,chord_id,fnames,composer
0,1,1,3/8,3/8,9/8,3,1,3/4,NaN,1/2,3/2,NaN,-4.0,56.0,NaN,0,Snarky_Puppy-Shapons_Vindaloo,Väsen
1,1,1,3/8,3/8,9/8,3,1,3/4,NaN,1/2,3/2,NaN,2.0,62.0,NaN,0,Snarky_Puppy-Shapons_Vindaloo,Väsen
2,1,1,3/8,3/8,9/8,3,1,3/4,NaN,1/2,3/2,NaN,-4.0,68.0,NaN,0,Snarky_Puppy-Shapons_Vindaloo,Väsen
3,2,2,0,0,7/8,4,1,1/4,NaN,1/4,1,NaN,1.0,55.0,NaN,2,Snarky_Puppy-Shapons_Vindaloo,Väsen
4,2,2,0,0,7/8,3,1,7/8,NaN,1/2,7/4,NaN,1.0,55.0,NaN,1,Snarky_Puppy-Shapons_Vindaloo,Väsen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456165,64,64,3/8,3/8,4/4,1,1,1/16,NaN,1/16,1,NaN,3.0,57.0,NaN,700,Kids Are Pretty People - Vincent Nilsson,Comp.osition: Thad Jones\nSoloing: Vincent Nil...
456166,64,64,7/16,7/16,4/4,1,1,1/16,NaN,1/16,1,NaN,0.0,60.0,NaN,701,Kids Are Pretty People - Vincent Nilsson,Comp.osition: Thad Jones\nSoloing: Vincent Nil...
456167,64,64,1/2,1/2,4/4,1,1,1/4,NaN,1/4,1,NaN,-1.0,65.0,NaN,702,Kids Are Pretty People - Vincent Nilsson,Comp.osition: Thad Jones\nSoloing: Vincent Nil...
456168,64,64,3/4,3/4,4/4,1,1,1/4,NaN,1/4,1,NaN,7.0,61.0,NaN,703,Kids Are Pretty People - Vincent Nilsson,Comp.osition: Thad Jones\nSoloing: Vincent Nil...
456169,65,65,0,0,4/4,1,1,1/4,NaN,1/4,1,NaN,2.0,62.0,NaN,704,Kids Are Pretty People - Vincent Nilsson,Comp.osition: Thad Jones\nSoloing: Vincent Nil...