In [155]:
import pandas as pd
from fractions import Fraction
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm
import music21 as m21
import ms3

In [190]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('/Users/Jessica/Documents/ERIP2025/Jessica-ERIP2025/')

from Importables import General as g

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [185]:
df = g.load_df()
df

,mc,mn,mc_onset,mn_onset,timesig,staff,voice,duration,gracenote,nominal_duration,...,pc,note,time,artist,workTitle,fnames,rel_paths,recording_year,label,ILS
0,1,1,0.3750,3/8,9/8,3,1,0.7500,NaN,1/2,...,8,Ab,1.3750,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,A-b5,"[A-, C, E--]"
1,1,1,0.3750,3/8,9/8,3,1,0.7500,NaN,1/2,...,2,D,1.3750,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,A-b5,"[A-, C, E--]"
2,1,1,0.3750,3/8,9/8,3,1,0.7500,NaN,1/2,...,8,Ab,1.3750,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,A-b5,"[A-, C, E--]"
3,2,2,0.0000,0,7/8,4,1,0.2500,NaN,1/4,...,7,G,2.0000,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,g5,"[G, D]"
4,2,2,0.0000,0,7/8,3,1,0.8750,NaN,1/2,...,7,G,2.0000,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,g5,"[G, D]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188620,64,64,0.3750,3/8,4/4,1,1,0.0625,NaN,1/16,...,9,A,64.3750,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,A7,"[A, C#, E, G]"
188621,64,64,0.4375,7/16,4/4,1,1,0.0625,NaN,1/16,...,0,C,64.4375,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,A7,"[A, C#, E, G]"
188622,64,64,0.5000,1/2,4/4,1,1,0.2500,NaN,1/4,...,5,F,64.5000,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,A7,"[A, C#, E, G]"
188623,64,64,0.7500,3/4,4/4,1,1,0.2500,NaN,1/4,...,1,C#,64.7500,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,A7,"[A, C#, E, G]"
188624,65,65,0.0000,0,4/4,1,1,0.2500,NaN,1/4,...,2,D,65.0000,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,Dm7,"[D, F, A, C]"

In [194]:
metadata = g.load_metadata()
metadata.head()

/opt/anaconda3/lib/python3.12/site-packages/music21/musicxml/xmlToM21.py:2226: MusicXMLWarning: Warning: measure 57 in part Pianois overfull: 4.1640625 > 4.0,assuming 4.0 is correct.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/music21/musicxml/xmlToM21.py:2226: MusicXMLWarning: Warning: measure 71 in part Pianois overfull: 8.08203125 > 8.0,assuming 8.0 is correct.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/music21/musicxml/xmlToM21.py:2226: MusicXMLWarning: Warning: measure 79 in part Pianois overfull: 4.01171875 > 4.0,assuming 4.0 is correct.
  warnings.warn(
/opt/anaconda3/lib/python3.12/site-packages/music21/musicxml/xmlToM21.py:5477: MusicXMLWarning: Could not import pedal: Error in getting PedalMark
  warnings.warn(f'Could not import {tag}: {excep}', MusicXMLWarning)

,rel_paths,fnames,last_mc,last_mn,KeySig,TimeSig,label_count,annotated_key,composer,workTitle,...,staff_7_instrument,staff_8_ambitus,staff_8_instrument,staff_9_ambitus,staff_9_instrument,transcribed_instruments,transcribed_sections,transposition,year_certain,key
0,by_Alexander_Booker,Snarky_Puppy-Shapons_Vindaloo,142,142,"1: 0, 113: -3, 134: 0","1: 9/8, 2: 7/8, 4: 9/8, 5: 7/8, 7: 9/8, 8: 7/8...",8,NaN,Väsen,Shapons Vindaloo,...,NaN,NaN,NaN,NaN,NaN,"ac-g, e-g, b, nyckelharpa",complete,Concert Key,1,c minor
1,by_Alexander_Booker,The_Fearless_Flyers-Ace_of_Aces,57,57,1: 3,1: 4/4,2,NaN,Smith/Dart/Wong/Lettieri/Stratton,Ace Of Aces,...,NaN,NaN,NaN,NaN,NaN,"g, b, dr",complete,Concert Key,1,A major
2,by_Alexander_Booker,Vulfpeck-Fugue_State,71,71,1: 0,1: 4/4,13,NaN,"Woody Goss, Jack Stratton",Fugue State,...,NaN,NaN,NaN,NaN,NaN,"ep, g, b, dr",complete,Concert Key,1,E- major
3,by_Carles_Margarit,12 Keys Blues - Bob Mintzer,156,156,1: 0,1: 4/4,169,NaN,NaN,12 Keys Blues,...,NaN,NaN,NaN,NaN,NaN,ts,solo,Bb,1,B- major
4,by_Carles_Margarit,26_2 - Coltrane (Concert Key),298,297,1: -1,"1: 4/4, 296: 2/4, 298: 4/4",347,NaN,John Coltrane,26-2,...,NaN,NaN,NaN,NaN,NaN,ts,complete,Concert Key,1,F major

In [210]:
subset = metadata[(metadata['workTitle'] == 'Four') | (metadata['workTitle'] == 'Blues By Five')]
subset = subset[subset['artists'].isin(['John Coltrane', 'Miles Davis'])]
subset[['workTitle', 'artists', 'key']]

        workTitle        artists       key
23  Blues By Five  John Coltrane  B- major
24  Blues By Five    Miles Davis  E- major
38           Four  John Coltrane  E- major
39           Four    Miles Davis   F major

In [257]:
def groupby_standard(df, length=3):
    # Step 1: Get unique (fnames, workTitle) pairs
    ref = df[['fnames', 'workTitle']].drop_duplicates()

    # Step 2: Group by workTitle → count how many files (fnames) per title
    ref_count = ref.groupby('workTitle').size().reset_index(name='count')

    # Step 3: Keep only titles with ≥ length files
    ref_filtered = ref_count[ref_count['count'] >= length]

    # Step 4: Filter big df to only those titles
    title_grouped = df[df['workTitle'].isin(ref_filtered['workTitle'])]

    ref_filtered = ref_filtered.sort_values(by='count', ascending=False)

    return title_grouped, ref_filtered

title_grouped, ref = groupby_standard(df, length=3)
ref

                           workTitle  count
74                       Giant Steps      9
200  There Will Never Be Another You      6
9             All The Things You Are      5
28                     Blues By Five      5
68                              Four      5
101                       Joy Spring      4
102                     Just Friends      4
190                    Tenor Madness      4
209                   Watermelon Man      4
17                     Autumn Leaves      3
26                        Blue Bossa      3
96                  Isn't She Lovely      3
139                             Oleo      3
174      Someday My Prince Will Come      3
181              Stella By Starlight      3

In [233]:
def groupby_artist(df, length=3):
    # Step 1: Get unique (fnames, artist) pairs
    ref = df[['fnames', 'artist']].drop_duplicates()

    # Step 2: Group by artist → count how many files (fnames) per title
    ref_count = ref.groupby('artist').size().reset_index(name='count')

    # Step 3: Keep only titles with ≥ length files
    ref_filtered = ref_count[ref_count['count'] >= length]

    # Step 4: Filter big df to only those titles
    artist_grouped = df[df['artist'].isin(ref_filtered['artist'])]

    ref_filtered = ref_filtered.sort_values(by='count', ascending=False)

    return artist_grouped, ref_filtered

artist_grouped, ref = groupby_artist(df, length=3)
ref

             artist  count
10       Chet Baker      8
16    Dexter Gordon      8
43      Miles Davis      8
4       Bob Mintzer      7
47     Paul Desmond      7
32    John Coltrane      6
41  Michael Brecker      5
56      Sonny Stitt      5
54    Sonny Rollins      5
57        Stan Getz      5
30    Joe Henderson      5
45   Mulgrew Miller      4
35    Keith Jarrett      4
39     Lester Young      3
5      Bob Reynolds      3
24      Hank Mobley      3
12     Chris Potter      3

In [237]:
def groupby_year(df, length=3):
    # Step 1: Get unique (fnames, artist) pairs
    ref = df[['fnames', 'recording_year']].drop_duplicates()

    # Step 2: Group by artist → count how many files (fnames) per title
    ref_count = ref.groupby('recording_year').size().reset_index(name='count')

    # Step 3: Keep only titles with ≥ length files
    ref_filtered = ref_count[ref_count['count'] >= length]

    # Step 4: Filter big df to only those titles
    year_grouped = df[df['recording_year'].isin(ref_filtered['recording_year'])]

    ref_filtered = ref_filtered.sort_values(by='count', ascending=False)

    return year_grouped, ref_filtered

year_grouped, ref = groupby_year(df, length=3)
ref

   recording_year  count
6            1956     16
12           1963     10
4            1954     10
26           1992      7
11           1962      6
8            1959      5
38           2012      5
23           1988      5
3            1952      4
32           2002      4
5            1955      4
10           1961      4
41           2015      4
35           2009      4
40           2014      3
36           2010      3
21           1986      3
28           1996      3
22           1987      3
18           1975      3
17           1974      3
13           1964      3
42           2017      3

In [265]:
# Group by artist, aggregate min and max
df['recording_year'] = pd.to_numeric(df['recording_year'], errors='coerce')

agg_df = (
    df.groupby('artist').agg(
        min_year=('recording_year', 'min'),
        max_year=('recording_year', 'max'),
        count=('workTitle', 'nunique')
    ).reset_index()
)
agg_df['year_range'] = agg_df['min_year'].astype(str) + "–" + agg_df['max_year'].astype(str)

agg_df[['artist', 'year_range', 'count']].sort_values(by='count', ascending=False).head(10)

             artist     year_range  count
43      Miles Davis  1954.0–1961.0      8
16    Dexter Gordon  1956.0–1976.0      8
4       Bob Mintzer  1992.0–2012.0      7
10       Chet Baker  1954.0–1988.0      7
32    John Coltrane  1956.0–1964.0      6
47     Paul Desmond  1959.0–1974.0      6
41  Michael Brecker  1978.0–2002.0      5
56      Sonny Stitt  1963.0–1963.0      5
57        Stan Getz  1955.0–1990.0      5
30    Joe Henderson  1963.0–1996.0      4