In [155]:
import pandas as pd
from fractions import Fraction
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm
import music21 as m21
import ms3

In [157]:
%load_ext autoreload
%autoreload 2

import sys
sys.path.append('/Users/Jessica/Documents/ERIP2025/Jessica-ERIP2025/')

from Importables import General as g

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [159]:
df = g.load_df()
df

,mc,mn,mc_onset,mn_onset,timesig,staff,voice,duration,gracenote,nominal_duration,...,chord_id,pc,note,time,artist,workTitle,fnames,rel_paths,recording_year,label
0,1,1,0.3750,3/8,9/8,3,1,3/4,NaN,1/2,...,0,8,Ab,1.3750,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,Ab(b5)
1,1,1,0.3750,3/8,9/8,3,1,3/4,NaN,1/2,...,0,2,D,1.3750,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,Ab(b5)
2,1,1,0.3750,3/8,9/8,3,1,3/4,NaN,1/2,...,0,8,Ab,1.3750,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,Ab(b5)
3,2,2,0.0000,0,7/8,4,1,1/4,NaN,1/4,...,2,7,G,2.0000,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,g5
4,2,2,0.0000,0,7/8,3,1,7/8,NaN,1/2,...,1,7,G,2.0000,Snarky Puppy,Shapons Vindaloo,Snarky_Puppy-Shapons_Vindaloo,by_Alexander_Booker,2015,g5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188620,64,64,0.3750,3/8,4/4,1,1,1/16,NaN,1/16,...,700,9,A,64.3750,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,A7
188621,64,64,0.4375,7/16,4/4,1,1,1/16,NaN,1/16,...,701,0,C,64.4375,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,A7
188622,64,64,0.5000,1/2,4/4,1,1,1/4,NaN,1/4,...,702,5,F,64.5000,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,A7
188623,64,64,0.7500,3/4,4/4,1,1,1/4,NaN,1/4,...,703,1,C#,64.7500,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,A7
188624,65,65,0.0000,0,4/4,1,1,1/4,NaN,1/4,...,704,2,D,65.0000,Vincent Nilsson,Kids Are Pretty People,Kids Are Pretty People - Vincent Nilsson,by_seemajorsheetmusic,1978,Dm7

In [166]:
df = g.load_df()
df = df[df['fnames'] == "Vulfpeck-Fugue_State"]

df_result = df[(df['mc'] == 40) & (df['mc_onset'] == Fraction("0"))]
df_result = df_result.iloc[0]['label']
df_result

nan

In [119]:
from music21 import harmony

def label_to_pcs(label):
    cs = harmony.ChordSymbol(label)
    pcs = sorted([p.pitchClass for p in cs.pitches])
    return pcs

In [114]:
def generate_pcs(df):

    pitchclass = df.groupby(by=['time', 'fnames']).agg({
        'mc': 'first',
        'mn': 'first',
        'mc_onset': 'first',
        'duration': 'first',
        'note': lambda x: list(set(x))  # collect unique notes as list
    }).reset_index()

    return pitchclass

In [116]:
generate_pcs(df)

,time,fnames,mc,mn,mc_onset,duration,note
0,1.00,12 Keys Blues - Bob Mintzer,1,1,0.00,1/8,[F]
1,1.00,Ad Lib Blues - Lester Young (Concert Key),1,1,0.00,1/8,[E]
2,1.00,All The Things You Are - Bob Mintzer (Concert ...,1,1,0.00,1/8,[Ab]
3,1.00,All The Things You Are - Lennie Neihaus (Conce...,1,0,0.00,1/8,[Eb]
4,1.00,All The Things You Are - Paul Desmond,1,1,0.00,1,[Ab]
...,...,...,...,...,...,...,...
123052,599.75,Deep Space _ Solar with rounded off Tempo Map,599,599,0.75,1/4,"[Eb, Bb, Ab, Db]"
123053,600.00,Deep Space _ Solar,600,600,0.00,1/4,"[C#, A, G, D]"
123054,600.00,Deep Space _ Solar with rounded off Tempo Map,600,600,0.00,1/4,"[C#, A, G, D]"
123055,600.50,Deep Space _ Solar,600,600,0.50,1/2,"[A, G, D]"
123056,600.50,Deep Space _ Solar with rounded off Tempo Map,600,600,0.50,1/2,"[A, G, D]"