# 5 - Neo-Riemannian Transformations

In [170]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [172]:
import pandas as pd
from fractions import Fraction
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm
import music21 as m21

import sys
sys.path.append('/Users/Jessica/Documents/ERIP2025/Jessica-ERIP2025/')

from Importables import General as g
from Importables import intervalanalysis_utils as ia
from Importables import tonnetz_utils as t

## Test: Final Thought - Kamasi Washington

In [174]:
metadata = g.load_metadata()
test = metadata[metadata['fnames'] == 'Final Thought - Kamasi Washington']
labels = g.load_labels(test)
labels.head()

,mc,mn,quarterbeats,quarterbeats_all_endings,duration_qb,mc_onset,mn_onset,timesig,staff,voice,harmony_layer,label,regex_match,artist,workTitle,fnames,rel_paths,recording_year,time,ILS
0,1,1,0,0,116.0,0.0,0,2/2,1,1,3,Dm,NaN,Kamasi Washington,Tenor Sax solo by Kamasi Washington\non Final ...,Final Thought - Kamasi Washington,by_Seth_Bailin,2015.0,1.0,"[D, F, A]"
1,30,30,116,116,8.0,0.0,0,2/2,1,1,3,E-,NaN,Kamasi Washington,Tenor Sax solo by Kamasi Washington\non Final ...,Final Thought - Kamasi Washington,by_Seth_Bailin,2015.0,30.0,"[E-, G, B-]"
2,32,32,124,124,8.0,0.0,0,2/2,1,1,3,Dm,NaN,Kamasi Washington,Tenor Sax solo by Kamasi Washington\non Final ...,Final Thought - Kamasi Washington,by_Seth_Bailin,2015.0,32.0,"[D, F, A]"
3,34,34,132,132,8.0,0.0,0,2/2,1,1,3,E-,NaN,Kamasi Washington,Tenor Sax solo by Kamasi Washington\non Final ...,Final Thought - Kamasi Washington,by_Seth_Bailin,2015.0,34.0,"[E-, G, B-]"
4,36,36,140,140,8.0,0.0,0,2/2,1,1,3,F,NaN,Kamasi Washington,Tenor Sax solo by Kamasi Washington\non Final ...,Final Thought - Kamasi Washington,by_Seth_Bailin,2015.0,36.0,"[F, A, C]"

In [188]:
transformations = t.transformation(labels)
transformations.value_counts(subset=['transformation']).reset_index(name='count')

  transformation  count
0            N/A     12
1              N      2
2              R      2
3              S      2